// Generated by https://quicktype.io

namespace MyCourse.Models.Options
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CoursesOptions
    {
        //[JsonProperty("PerPage")]
        public long PerPage { get; set; }

        //[JsonProperty("Order")]
        public CoursesOrderOptions Order { get; set; }
    }

    public partial class CoursesOrderOptions
    {
        //[JsonProperty("By")]
        public string By { get; set; }

        //[JsonProperty("Ascending")]
        public bool Ascending { get; set; }

        //[JsonProperty("Allow")]
        public string[] Allow { get; set; }
    }

    /*
    public partial class CoursesOptions
    {
        public static CoursesOptions FromJson(string json) => JsonConvert.DeserializeObject<CoursesOptions>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this CoursesOptions self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
    */
}
